#!/usr/bin/env python3
"""
_emit_active_env.py — Read 00_config.yaml and emit pipeline/_active_gwas.env

The env file is a plain bash export file that downstream bash scripts (02, 03,
and any future ones) source instead of parsing YAML in shell. This makes
00_config.yaml the SINGLE source of truth for all GWAS-specific values.

Usage from a bash script:
    python3 pipeline/_emit_active_env.py
    source pipeline/_active_gwas.env

The env file is regenerated on every run (idempotent, no stale values) and is
gitignored so a teammate's "active_gwas" choice doesn't pollute the repo.

To switch GWAS:
    1. Edit `active_gwas:` in pipeline/00_config.yaml
    2. Re-run the pipeline. _active_gwas.env regenerates automatically.

To add a new GWAS:
    1. Add a new block under `gwas:` in pipeline/00_config.yaml. Required
       fields beyond the existing schema: `file_prefix` (string, snake_case;
       used as the prefix for all generated files, e.g. "scz_pgc3").
    2. Set `active_gwas: "<your_new_key>"`.
    3. Run the pipeline. No edits to any scripts needed.
"""

import datetime
import sys
import yaml
from pathlib import Path


def shell_quote(value):
    s = str(value)
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")
    return f'"{s}"'


def main():
    pipeline_dir = Path(__file__).resolve().parent
    config_path = pipeline_dir / "00_config.yaml"

    if not config_path.exists():
        sys.exit(f"[_emit_active_env] ERROR: config not found at {config_path}")

    with open(config_path) as f:
        c = yaml.safe_load(f)

    active = c.get("active_gwas")
    if not active:
        sys.exit("[_emit_active_env] ERROR: 'active_gwas' not set in 00_config.yaml")
    if active not in c.get("gwas", {}):
        sys.exit(f"[_emit_active_env] ERROR: active_gwas '{active}' has no block under 'gwas:'")

    g = c["gwas"][active]
    paths = c["paths"]
    magma = c["magma"]

    file_prefix = g.get("file_prefix", active)
    output_folder = g["output_folder"]
    results_dir = f"{paths['results_dir']}/{output_folder}"

    # file_base = "<file_prefix>.no_heading" — preserves Duncan's MAGMA --out
    # convention where the input sumstats filename propagates to output names.
    file_base = f"{file_prefix}.no_heading"

    L = []
    L.append("# =================================================================")
    L.append("# Auto-generated by pipeline/_emit_active_env.py — DO NOT EDIT")
    L.append("# Source from bash: source pipeline/_active_gwas.env")
    L.append(f"# Generated:  {datetime.datetime.now(datetime.timezone.utc).isoformat()}")
    L.append(f"# active_gwas: {active}")
    L.append("# =================================================================")
    L.append("")
    L.append("# --- Identity ---")
    L.append(f"export ACTIVE_GWAS={shell_quote(active)}")
    L.append(f"export GWAS_NAME={shell_quote(g.get('name', active))}")
    L.append("")
    L.append("# --- Folder + file naming ---")
    L.append(f"export OUTPUT_FOLDER={shell_quote(output_folder)}")
    L.append(f"export FILE_PREFIX={shell_quote(file_prefix)}")
    L.append(f"export FILE_BASE={shell_quote(file_base)}")
    L.append("")
    L.append("# --- Computed paths (all relative to project root) ---")
    L.append(f"export RESULTS_DIR={shell_quote(results_dir)}")
    L.append(f"export RUN_LOG={shell_quote(f'{results_dir}/run.log')}")
    L.append(f"export SUMSTATS_FILE={shell_quote(f'{results_dir}/{file_base}')}")
    L.append(f"export SNPLOC_FILE={shell_quote(f'{results_dir}/snploc_{file_prefix}')}")
    L.append(f"export STEP1_PREFIX={shell_quote(f'{results_dir}/{file_base}.step1')}")
    L.append(f"export STEP1_ANNOT={shell_quote(f'{results_dir}/{file_base}.step1.genes.annot')}")
    L.append(f"export STEP2_PREFIX={shell_quote(f'{results_dir}/{file_base}.step2')}")
    L.append(f"export STEP2_GENES_RAW={shell_quote(f'{results_dir}/{file_base}.step2.genes.raw')}")
    L.append(f"export STEP2_GENES_OUT={shell_quote(f'{results_dir}/{file_base}.step2.genes.out')}")
    L.append(f"export STEP2_LOG={shell_quote(f'{results_dir}/{file_base}.step2.log')}")
    L.append(f"export CELLTYPE_OUT_PREFIX={shell_quote(f'{results_dir}/Siletti_l2_conti-spe_{output_folder}')}")
    L.append("")
    L.append("# --- Reference data paths ---")
    L.append(f"export GENE_LOC={shell_quote(paths['gene_loc'])}")
    L.append(f"export G1000_PREFIX={shell_quote(paths['g1000_ref_prefix'])}")
    L.append(f"export SPECIFICITY_MATRIX={shell_quote(paths['specificity_matrix'])}")
    L.append("")
    L.append("# --- MAGMA parameters ---")
    L.append(f"export REQ_VERSION={shell_quote(magma['required_version'])}")
    L.append(f"export WIN_UP={shell_quote(magma['gene_window_upstream_kb'])}")
    L.append(f"export WIN_DN={shell_quote(magma['gene_window_downstream_kb'])}")
    L.append(f"export MODEL_DIRECTION={shell_quote(magma['model_direction'])}")
    L.append("")
    L.append("# --- Sumstats output column names (convention set by 01_prep_sumstats.py) ---")
    L.append('export SNP_COL="ID"')
    L.append('export P_COL="PVAL"')
    L.append('export N_COL="NEFF"')
    L.append("")

    env_path = pipeline_dir / "_active_gwas.env"
    env_path.write_text("\n".join(L))
    print(f"[_emit_active_env] Wrote {env_path.relative_to(pipeline_dir.parent)} "
          f"for active_gwas={active}", file=sys.stderr)


if __name__ == "__main__":
    main()
